runtime: nodejs8
service: gosenchoen
instance_class: F2
automatic_scaling:
  max_instances: 5
  min_instances: 0
  target_cpu_utilization: 0.75
env_variables:
  FONTCONFIG_PATH: "/srv/fonts/"
  HCEP_USE_CHROMIUM: "true"
  HCEP_PORT: 8080
